language: python
python:
- 2.7
addons:
  postgresql: '9.3'
env:
  - DJANGO_SETTINGS_MODULE=ap.settings.travis
install:
  - pip install -r requirements/dev.txt
before_script:
  - psql -c 'create database djattendance;' -U postgres
  - python ap/manage.py makemigrations accounts aputils books classes houses localities rooms services teams terms attendance absent_trainee_roster dailybread leaveslips lifestudies meal_seating schedules syllabus verse_parse
script:
  - python ap/manage.py migrate --noinput
#  - coverage run ap/runtests.py
#  - coverage report
notifications:
  email:
    recipients:
      - attendanceproj@gmail.com
#after_success:
#  - coveralls
deploy:
  provider: heroku
  api_key:
    secure: Erc8ZoPuwl+QTRuOn1pDRRBaLCnYgDPYBSxWbn1OSDei1jfg3euMdIbO1UwBNfpLMeY+VOP9e7YrXa5qdGxEEJdUnY5gQ0K/uYl+Z7juARduabkNZyUV/8tD4zzDo2Fiucvwtk8GF75HmzkED5W316NEnJ00vpBoxIC5ajNw1Qk=
  app: djattendance
  on:
    repo: attendanceproject/djattendance
    branch: dev
